HTTP/1.1 302 Found
Cache-Control: private
Content-Length: 256
Content-Type: text/html; charset=UTF-8
Date: Thu, 08 Jun 2017 08:57:11 GMT
Location: http://www.google.it/?gfe_rd=cr&ei=xxx
Referrer-Policy: no-referrer
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.it/?gfe_rd=cr&amp;ei=xxx">here</A>.
</BODY></HTML>
